#!/bin/bash

if [ $# -eq 1 ]
    then
        if [[ -f $1 ]]; then
            INPUT_DIR=$(dirname $1)
            INPUT_FILE=$(basename $1)
            SCRIPT_DIR=$(dirname $0)
            $SCRIPT_DIR/bin/lattec <$1 >tmpfile
            if [ $? -ne 0 ]
                then
                    rm tmpfile
                    exit 1
            else
                llvm-link -S tmpfile $SCRIPT_DIR/lib/runtime.ll >$INPUT_DIR/${INPUT_FILE%%.*}\.ll
                rm tmpfile
                llvm-as $INPUT_DIR/${INPUT_FILE%%.*}\.ll
            fi
        else
            echo "Usage: $0 <name_of_input_file>"
            exit 1
        fi
else
    echo "Usage: $0 <name_of_input_file>"
    exit 1
fi
